# Generated by Django 3.1.3 on 2020-11-19 04:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Horas_medicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('diagnostico', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_boxes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_principal.boxes')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellidos', models.TextField()),
                ('rut', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_principal.generos')),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellidos', models.TextField()),
                ('rut', models.TextField()),
                ('contrasena', models.TextField()),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_principal.generos')),
            ],
        ),
        migrations.CreateModel(
            name='Llamada_medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llamadas', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_hora_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_principal.horas_medicas')),
                ('id_notificaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_principal.notificaciones')),
            ],
        ),
        migrations.AddField(
            model_name='horas_medicas',
            name='id_nombre_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_principal.medicos'),
        ),
        migrations.AddField(
            model_name='horas_medicas',
            name='id_nombre_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_principal.pacientes'),
        ),
    ]
