# Generated by Django 3.1.3 on 2020-11-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horas_medicas',
            old_name='id_nombre_medico',
            new_name='id_medico',
        ),
        migrations.RenameField(
            model_name='horas_medicas',
            old_name='id_nombre_paciente',
            new_name='id_paciente',
        ),
        migrations.AlterField(
            model_name='medicos',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
