# Generated by Django 3.1.3 on 2020-11-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_principal', '0002_auto_20201119_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horas_medicas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
