# Generated by Django 3.1.3 on 2020-11-19 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_principal', '0003_auto_20201119_0409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boxes',
            new_name='Boxe',
        ),
        migrations.RenameModel(
            old_name='Generos',
            new_name='Genero',
        ),
        migrations.RenameModel(
            old_name='Horas_medicas',
            new_name='Horas_medica',
        ),
        migrations.RenameModel(
            old_name='Medicos',
            new_name='Medico',
        ),
        migrations.RenameModel(
            old_name='Notificaciones',
            new_name='Notificacione',
        ),
        migrations.RenameModel(
            old_name='Pacientes',
            new_name='Paciente',
        ),
    ]
