# Generated by Django 3.1.3 on 2020-11-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_principal', '0007_auto_20201124_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='contrasena',
        ),
    ]
