# Generated by Django 3.1.3 on 2020-11-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_principal', '0008_remove_medico_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacione',
            name='published_date',
        ),
        migrations.AddField(
            model_name='notificacione',
            name='nombrecompleto',
            field=models.TextField(default='Pedrito'),
        ),
        migrations.AddField(
            model_name='notificacione',
            name='rut',
            field=models.TextField(default='91.111.111-1'),
        ),
    ]
